### ISSUE TITLE
证书会自动更新吗？

### ISSUE THREAD

**Issue by zerozero123** [mark-hans/trojan-wiz#2]
![image](https://user-images.githubusercontent.com/39449060/52896744-b63aa500-3206-11e9-9e45-12cdda408351.png)
在端口一栏，有看到nginx。
我平常使用的v2ray CDN脚本里，开源作者在caddy设置中设置自动更新SSL证书功能。大佬，你这个Nginx有吗？

**Comment by mark-hans** [comment]
证书更新问题我是有考虑，现在工作很忙，手里项目很多，暂时没有动

**Comment by zerozero123** [comment]
大佬，有空就往脚本里加吧😂😂

mark-hans <notifications@github.com> 于2019年2月19日周二 下午7:36写道：

**Comment by mark-hans** [comment]
证书自动续期已经加入
