### ISSUE TITLE
脚本相关

### ISSUE THREAD

**Issue by zerozero123** [mark-hans/trojan-wiz#3]
为啥子你脚本构成代码是加密的呢？可以开发让别人检查不，这样才会有更多的人来使用

**Comment by mark-hans** [comment]
代码在ins.sh~文件里面，运行build.sh是构建。加密只是为压缩大小，回忆下载速度。

**Comment by zerozero123** [comment]
![image](https://user-images.githubusercontent.com/39449060/55276498-173db880-532f-11e9-9b37-eecad1917e7d.png)貌似是加密的
