### ISSUE TITLE
![image](https://user-images.githubusercontent.com/39449060/55276498-173db880-532f-11e9-9b37-eecad1917e7d.png)貌似是加密的

### ISSUE THREAD

**Issue by zerozero123** [mark-hans/trojan-wiz#4]
![image](https://user-images.githubusercontent.com/39449060/55276498-173db880-532f-11e9-9b37-eecad1917e7d.png)貌似是加密的

_Originally posted by @zerozero123 in https://github.com/mark-hans/trojan-wiz/issues/3#issuecomment-478243788_

**Comment by mark-hans** [comment]
关于脚本加密问题是不存在的，所有构建命令都已经开源。执行build.sh即可
