### ISSUE TITLE
脚本加密问题，别关掉我这个issue

### ISSUE THREAD

**Issue by zerozero123** [mark-hans/trojan-wiz#5]
老哥，你作为一名开发者，我站在你的角度考虑问题———这个逼怎么老是考虑我的脚本加密问题，事实上的确存在，我用好几种编辑软件打卡下载好的ins.sh文件，看到后面都是乱码的）。对我的不信任，让我想把这个项目给关了，你可别这么做
![image](https://user-images.githubusercontent.com/39449060/55340009-62460000-54d6-11e9-9a7c-3de398b6b0d7.png)
作为一名使用者，我能力有限，我更喜欢脚本，可是我在使用脚本对代码加密非常反感，我想你也会有这样的想法，所以你自己能不能检查下为啥子打开ins.sh之后代码全部乱码了。而且我找人看你的代码构建时，那人跟我有一样的想法，就是代码被保护了

**Comment by zerozero123** [comment]
感谢你的付出，更新了自动更新证书功能

**Comment by zerozero123** [comment]
可以建立caddy插件，
执行
echo ":80 {
gzip
proxy / http://监听网站
}" > /usr/local/caddy/Caddyfile

**Comment by mark-hans** [comment]
我的问题已回应，请看视频https://youtu.be/zzF3AMf0_qI
